#!/bin/bash
# see this link for other options 
# http://www.coppeliarobotics.com/helpFiles/en/commandLine.htm

#cd $COPPELIASIM_ROOT_DIR

#pwd

ARGS=""
if [[ $2 -gt 0 ]]; then
   ARGS="-h -s -q"
fi


~/Programs/CoppeliaSim_Edu_V4_1_0_Ubuntu16_04/coppeliaSim.sh $ARGS -g"$3" "$1"



